### ISSUE TITLE
"Permission is invalid" error when using Node 18

### ISSUE THREAD

**Issue by vetruvet** [akamai/cli-edgeworkers#110]
When using Node 18, the CLI gives a "Permission is invalid" error. Switching to Node 16 or 14 resolves the error.

**Steps to reproduce:**

1. Install and configure Akamai CLI and install edgeworkers package
2. run the following (assuming `nvm` is used to manage node versions)

```
nvm use 16
akamai edgeworkers list-ids
nvm use 18
akamai edgeworkers list-ids
```

**Expected results:** CLI works on both node versions.
**Actual results:** CLI only works on pre-18 versions.

Not sure if the root cause of this is in the underlying [edgegrid](https://github.com/akamai/AkamaiOPEN-edgegrid-node) package – if it is, please let me know and I can open an issue there instead.

Similar issue in property-manager package: https://github.com/akamai/cli-property-manager/issues/79

**Comment by bmatthew** [comment]
Hey Valera, thanks for raising this issue.

I'm trying to reproduce the problem -- apologies but I'm not a regular nvm user so let's see how close I am to getting this right.

```bash
macbook:~$ node --version
v14.17.3
macbook:~$ nvm use 18
N/A: version "v18" is not yet installed.

You need to run `nvm install 18` to install and use it.
macbook:~$ nvm install 18
Downloading and installing node v18.12.1...
Downloading https://nodejs.org/dist/v18.12.1/node-v18.12.1-darwin-x64.tar.xz...
######################################################################################################################################################################################### 100.0%
Computing checksum with shasum -a 256
Checksums matched!
Now using node v18.12.1 (npm v8.19.2)
Creating default alias: default -> 18 (-> v18.12.1)
macbook:~$ node --version
v18.12.1
macbook:~$ akamai edgeworkers list-ids
------------------------------------------------------------------------------------------------------------
--- The following EdgeWorker Ids are currently registered for account: redacted, group: any, ewId: any ---
------------------------------------------------------------------------------------------------------------
┌─────────┬──────────────┬──────────────────────────┬─────────┬────────────────┐
│ (index) │ edgeWorkerId │           name           │ groupId │ resourceTierId │
├─────────┼──────────────┼──────────────────────────┼─────────┼────────────────┤
│    0    │     3654     │     'HeaderAddition'     │  61923  │      200       │
...
└─────────┴──────────────┴──────────────────────────┴─────────┴────────────────┘
macbook:~$ 
```

It looks to be working to me, is there something else that might be causing some trouble with node 18 on your system?

Just to see if it might be an issue with the CLI version installed, this is what I have on my system right now:

```bash
macbook:~$ akamai --version
akamai version 1.5.2
macbook:~$ akamai edgeworkers --version
1.6.0
macbook:~$ 
```

**Comment by vetruvet** [comment]
I'm running the same versions as you. To get some additional debugging information, I tried running it again with both node versions ... and the issue seems to be resolved now (though I have not updated node, akamai, or the edgeworkers package since) ... shot in the dark, but maybe it was some server-side configuration change? Either way, closing this as it seems to work fine for now
