### ISSUE TITLE
akamai Install not working

### ISSUE THREAD

**Issue by k-leonids** [akamai/cli-edgeworkers#153]
Can we run the following command in the latest package.json on Windows (cmd or powershell)? 
Installation on Windows is not working.

// package.json v.18.1 current
line 10   "postinstall": "if test \"$NODE_ENV\" != \"production\" ; then npm run build ; fi",

// package.json v1.7.3
line 10    "postinstall": "npm run build",

// debug log
> akamai install edgeworkers
 DEBUG[0000] Checking for upgrades
 DEBUG[0000] INSTALL START             command=install
(snip)
  INFO[0003] package.json found, running npm package manager command=install
Installing... [=======   ] DEBUG[0031] Unable execute package manager (C:\Users\user\AppData\Roaming\nvm\v20.17.0\npm.cmd install):
"$NODE_ENV" was unexpected at this time.
npm error code 1
npm error path C:\Users\user\\.akamai-cli\src\cli-edgeworkers
npm error command failed
npm error command C:\windows\system32\cmd.exe /d /s /c if test "$NODE_ENV" != "production" ; then npm run build ; fi
npm error A complete log of this run

**Comment by kyleli-akamai** [comment]
Hi @k-leonids , thank you for opening this ticket. This issue is expected to be fixed in the latest version (ie, 1.9.0) released this morning, so may I ask you to update and try again?

**Comment by k-leonids** [comment]
I successfully confirmed that I could install it. Thank you for your quick response.
